/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconFolderOpened: typeof import('@element-plus/icons-vue')['FolderOpened']
    ElIconQuestionFilled: typeof import('@element-plus/icons-vue')['QuestionFilled']
    ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
    ElIconView: typeof import('@element-plus/icons-vue')['View']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FileInput: typeof import('./components/FileInput.vue')['default']
    GraphicsFilter: typeof import('./components/GraphicsFilter.vue')['default']
    NeedlesTable: typeof import('./components/NeedlesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleTexture: typeof import('./components/SimpleTexture.vue')['default']
    TaraScaffoldVuer: typeof import('./components/TaraScaffoldVuer.vue')['default']
    UrlFileReader: typeof import('./components/UrlFileReader.vue')['default']
  }
}
